### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by tanghao123th** [spec-org/gfcc#10]
Hi,excuse me.When I **cd build and make**,I encountered the following error:
![image](https://user-images.githubusercontent.com/51874604/167754232-3175659b-d586-4133-967e-86fd49949866.png)
Ask me what I might have done wrong?

**Comment by ajaypanyala** [comment]
@tanghao123th Just to confirm, does this error show up at [Step 2](https://github.com/spec-org/gfcc/blob/master/docs/install.md#step-3-building-the-gfcc-library) ?

**Comment by tanghao123th** [comment]
Yes,this error show up at Step 2.
(https://github.com/spec-org/gfcc/blob/master/docs/install.md#step-3-building-the-gfcc-library)

**Comment by ajaypanyala** [comment]
Can I get the complete output of the `cmake ..` and `make` commands ?

**Comment by tanghao123th** [comment]
Hi,Here I type **cmake ..** The results of the:
![image](https://user-images.githubusercontent.com/51874604/167757191-f1d95f5e-112a-4f1b-8f8d-c2e0694ac249.png)

**Comment by ajaypanyala** [comment]
This looks good. If you can also save the output of `make` to a file and send it over, I can try to take a look.

**Comment by tanghao123th** [comment]
Hi, sorry for the late reply. The previous server took too long to compile and was always disconnected. The problem was resolved after I replaced the server. Thank you for your help.
