### ISSUE TITLE
Problems with using the GFCC Library

### ISSUE THREAD

**Issue by tanghao123th** [spec-org/gfcc#13]
**Excuse me,I run my program using cmake to call the library in the gfcc_install directory, When I type **make** in the Build folder, I get the following error:**
![image](https://user-images.githubusercontent.com/51874604/178638272-9fce66d0-d14a-4037-8298-c9ac0bb4326e.png)

### **This is my program structure.**
![image](https://user-images.githubusercontent.com/51874604/178638599-86b51160-6cdd-466f-885c-f02a6cb9fe0e.png)
![image](https://user-images.githubusercontent.com/51874604/178638633-506c0ecd-7b80-4f44-aded-3663e4abf1a1.png)

### This is my GFCC_install directory structure
![image](https://user-images.githubusercontent.com/51874604/178638998-fb736bf8-8431-4abd-8fa1-69571bf41c90.png)

**Comment by ajaypanyala** [comment]
@tanghao123th Unfortunately, the current code cannot be used as a library, but it will be in the future. The easiest way for now would be to directly edit the files [here](https://github.com/spec-org/gfcc/tree/master/src/gfcc) to achieve what you want. Could you elaborate a bit more what you are trying to do in your `main.cpp` ?

**Comment by tanghao123th** [comment]
Thank you very much for your reply！

**Comment by tanghao123th** [comment]
### I want to do a simple tensor operation using the GFCC Library. As shown below:
![image](https://user-images.githubusercontent.com/51874604/178929418-af4a823f-0dee-4c69-b2f5-f81e45eca7fd.png)

### I use the [https://github.com/spec-org/gfcc/blob/master/contrib/TAMM/tests/tamm/Test_Mult_Ops.cpp](url)

**Comment by ajaypanyala** [comment]
@tanghao123th I see. In this case you just need to use the underlying `TAMM` tensor algebra library which was used to develop the GFCC application code. This is very simple. Please modify the `CMakeLists.txt` from your own demo program folder to the following:

```
cmake_minimum_required(VERSION 3.22.0)
project(test LANGUAGES C CXX Fortran)

find_package(TAMM)

add_executable(main main.cpp)
target_link_libraries(main tamm::tamm)
```
You can invoke it as:
`cmake .. -DCMAKE_PREFIX_PATH=/home/th/gfcc_install -DCMAKE_CXX_FLAGS_INIT="-std=c++17"`

When using the file  [here](https://github.com/spec-org/gfcc/blob/master/contrib/TAMM/tests/tamm/Test_Mult_Ops.cpp), you *do not need* the `includes` in [the first 3 lines](https://github.com/spec-org/gfcc/blob/master/contrib/TAMM/tests/tamm/Test_Mult_Ops.cpp#L1-L3), just including the `tamm` [header](https://github.com/spec-org/gfcc/blob/master/contrib/TAMM/tests/tamm/Test_Mult_Ops.cpp#L4) is sufficient.

Also note to compile your demo program, you need to use the same compilers, cmake, MPI, etc version that were used to build the GFCC code.

**Comment by tanghao123th** [comment]
Thank you so much for your help! I have solved the problem successfully.
