### ISSUE TITLE
Questions with using the underlying TAMM Algebra Library

### ISSUE THREAD

**Issue by tanghao123th** [spec-org/gfcc#14]
Excuse me, I read the documentation [here](https://github.com/spec-org/gfcc/tree/master/contrib/TAMM/dox) but I didn't find anything about how to print out a Tensor.So,I want to know what function will print out a tensor that I've created.
For example,I've created a **Tensor A** using code like this, and then I want to print out the Tensor information (the size of **Tensor A**, the values of the elements it contains and so on)

`TiledIndexSpace MO{MO_is, 10}, AO{AO_is, 10}; `
`Tensor<double> A{MO, AO};`

**Comment by ajaypanyala** [comment]
@tanghao123th Sorry about that. `TAMM` will be released as a separate library later this year and will be better documented at that point. For now, please feel free to ask any questions here until that happens. To print a tensor, there are couple of options:

NOTE: `filename` argument below is optional. If not provided, the tensor is printed to standard output.
- `print_tensor(A, filename)` -> this routine only prints values < 1e-13
- `print_tensor_all(A, filename)` -> this routine prints all values (including zeros)

You might find the following code more useful if you need each value printed along it's index in the tensor:

```
    ExecutionContext ec_dense{pg, DistributionKind::dense, MemoryManagerKind::ga}; //create ec_dense once
    Tensor<T> X = to_dense_tensor(ec_dense,A);
    print_dense_tensor(X,filename);
    Tensor<T>::deallocate(X);
```

**Comment by tanghao123th** [comment]
I apologize for the error in the title.
Thank you very much for your patience. I have solved the problem successfully.
