### ISSUE TITLE
Problems encountered executing the GF_CCSD file

### ISSUE THREAD

**Issue by tanghao123th** [spec-org/gfcc#15]
Excuse me, When I typed `mpirun -n 2 $GFCC_INSTALL_PATH/bin/GF_CCSD $GFCC_SRC/tests/cytosine.json`  in the ~/gfcc_src/build file, 
![image](https://user-images.githubusercontent.com/51874604/180602723-b056a232-897b-4842-a1ae-828fcdf7060e.png)
I encountered the following problem:
![image](https://user-images.githubusercontent.com/51874604/180602619-a47af610-ba38-4516-acd2-fa555400a0d1.png)
How should I deal with it?

When I typed `mpirun -n 2 $GFCC_INSTALL_PATH/bin/GF_CCSD $GFCC_SRC/tests/co.json`  in the ~/gfcc_src/build file,I was able to successfully get the run results.

**Comment by ajaypanyala** [comment]
You mentioned at the end of your message that you were able to successfully run and get the results. So is the problem resolved ?

**Comment by tanghao123th** [comment]
I'm sorry I didn't describe the problem clearly.
I executed two commands in ~/gfcc_src/build file:
1.mpirun -n 2 $GFCC_INSTALL_PATH/bin/GF_CCSD $GFCC_SRC/tests/cytosine.json.
2.mpirun -n 2 $GFCC_INSTALL_PATH/bin/GF_CCSD $GFCC_SRC/tests/co.json.

The first command does not succeed in getting the result, but the second one does. The input JSON files for these two commands are different. Is this the cause of the problem?

**Comment by ajaypanyala** [comment]
The input json files will be different since they are different systems. I ran the first case just now on my end. It works fine. Could you please delete the folder "~/gfcc_src/build/cytosine.6-31++g*_files" and re-run it again?

**Comment by tanghao123th** [comment]
Thank you for your reply！I have successfully solved the problem.
