### ISSUE TITLE
What does CD_CCSD mean?

### ISSUE THREAD

**Issue by tanghao123th** [spec-org/gfcc#16]
I wonder what exactly CD_CCSD means? CCSD(T) refers to the Coupled Cluster single-double-triple. But I couldn't find the meaning of CD_CCSD in the query.

**Comment by ajaypanyala** [comment]
CD here stands for Cholesky decomposition of the Two-Electron Integral Tensor. More details can be found in [this](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.7b00605) paper.

**Comment by tanghao123th** [comment]
Thank you very much for your answer!
