### ISSUE TITLE
Run the project in conda

### ISSUE THREAD

**Issue by tanghao123th** [spec-org/gfcc#9]
Hi,excuse me,how do I run this project in conda?Which dependencies should I install in the Conda environment?

**Comment by ajaypanyala** [comment]
@tanghao123th It is not possible to run this project with Conda.

**Comment by tanghao123th** [comment]
Thank your reply!
When I run the project using a remote server(linux), I encounter the following error:
![image](https://user-images.githubusercontent.com/51874604/167575406-17ea51aa-a1e2-4207-8c04-0b16f40beb90.png)
I don't have administrative source access on this server.In other words,I can't execute a command like **sudo apt-get install build-essential**.what should I do?

**Comment by ajaypanyala** [comment]
Do you have a previously installed folder from an older build whose path is specified by the cmake option `CMAKE_INSTALL_PREFIX`. That is, could you please check if the folder you specified with `$GFCC_INSTALL_PATH` exists and delete it ? Once deleted, you can try a new build again.

**Comment by tanghao123th** [comment]
Thank you very much!
I succeeded in solving the problem.
